config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :posts do
    resources :comments
  end

  root to: 'posts#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
    
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "insomnia3"		
		if page_title.empty?
			base_title
		else
			"#{base_title}" | "#{page_title}"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete comment', [comment.post, comment],
              method: :delete, data: {confirm: 'sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |c| %>

<p>
  <%= c.label :commenter %><br>
  <%= c.text_field :commenter %>
</p>

<p>
  <%= c.label :comment %><br>
  <%= c.text_area :body %>
</p>

<p>
  <%= c.submit %>
</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Insomnia3", posts_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", posts_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">

<div id ="user_nav">
  <% if user_signed_in? %>
    Signed in as  <%= current_user.email %>. Not you?
    <%= link_to "Edit profile", edit_user_registration_path %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |p| %>

<p>
  <%= p.label :title %> <br> 
  <%= p.text_field :title %>
<p>

<p>
  <%= p.label :body %> <br> 
  <%= p.cktext_area :body %>
<p>

<p>
  <%= p.submit %> 
<p>

<% end %>

app/views/posts/edit.html.erb
<h1>Post edit</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>


<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="2"></th>
  </tr>
    
  <% @posts.each do |p| %>
   <tr>
    <td><%= p.title %></td>
    <td><%= p.body.html_safe %></td>
    <td><%= link_to 'Show', p %></td>
    <td><%= link_to 'Edit', edit_post_path(p) %></td>
    <td><%= link_to 'Delete', post_path(p), method: :delete, data: {confirm: 'sure?' } %></td>
  <% end %>
</table>
<br>
<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>Post new</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>	

app/views/posts/show.html.erb
<h1>Post show</h1>

<p>
  <strong>title</strong><br>
  <%= @post.title %>
</p>

<p>
  <strong>body</strong><br>
  <%= @post.body.html_safe %>
</p>

<h3>Comments:</h3>
<%= render @post.comments %>

<h4>Add a comment:</h4>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Back', posts_path %>